### PR TITLE
Modularized Python-Package (Python Files)

### PR DESCRIPTION
**Pull request by ric-evans**
Merge the two Skymap Scanners, preserving the physics code of the currently running/updated version (`python/`) and the cloud-communication code of the "Pulsar" version (`cloud_tools/`). See https://github.com/icecube/skymap_scanner/pull/24 and https://github.com/icecube/skymap_scanner/issues/19). This merged version uses a server-client (1:N) model.

We start with preserving all the IceTrays, in future PRs this may change. This PR is diff-friendly (no code formatting/ radical refactoring).

### Summary
Code is combined from `python/` (aka the SVN/ current skaymap scanner) and `cloud_tools/`:
- `python/`
	+ The core scanning logic/ IceTray Modules: 
		- `SendPixelsToScan`, 
		- all the Millipede modules, 
		- `FindBestRecoResultForPixel`, 
		- `CollectRecoResults`
- `cloud_tools/`
	+ Strictly the Pulsar logic (`pulsar_icetray.py`)
		- `AcknowledgeReceivedPFrame`, 
		- `PulsarClientService`, 
		- `ReceivePFrameWithMetadata`, 
		- `ReceiverService`, and 
		- `SendPFrameWithMetadata`

### Important Notes ~and Desperate Review Requests~
1. The Pulsar Version (`cloud_tools/`) used a 4-service model (1 producer, N workers, M collectors, and P savers). The "producer", "collector", and "saver" have been merged into one server instance. This allows sharing state between the top and bottom of the pipelines (i.e. `state_dict`). Since the main computation load is in the "workers" (now clients), we can simplify the model.
1. ~The Pulsar Version employs a "metadata topic", I'm not sure what's going on here, but it looks very detailed. **Please review this if you are able.**~
	+ ~Also look out https://github.com/icecube/skymap_scanner/blob/master/cloud_tools/collect_pixels.py#L27 and how this differs from the `FindBestRecoResultForPixel` in `skymap_scanner/server/perform_scan.py`/`python/perform_scan.py`~
   + **Update:** Thanks @claudiok, I learned enough about this to strip it out. A replacement scheme is being designed.
1. ~There looks to be a BIG difference between how the two existing versions distribute their pixels/scans to their workers. **Please review this if you are able.** I do not know what is best/ will work here. "I'm an engineer, not a scientist"~
	+	~`python/`: uses `numclients`~
	+  ~`cloud_tools/` uses `nside`, `area_center_nside`, `area_center_pixel`, `area_num_pixels`, `pixel_list`~
    + **Update:** Thanks @mlincett, it turns out this wasn't science after all :smile: It's been stripped out, now we can have infinite clients!

#### Server Code (`skymap_scanner/server/perform_scan.py`):
- `kdiff3 skymap_scanner/server/perform_scan.py python/perform_scan.py`
     + a lot of similar code
- `kdiff3 skymap_scanner/server/perform_scan.py cloud_tools/send_scan.py`
     + `send_scan_icetray()` vs `send_scan()`
	 + Pulsar Logic
- `kdiff3 skymap_scanner/server/perform_scan.py cloud_tools/collect_pixels.py`
     + `collect_and_save_pixels_icetray()` vs `collect_and_save_pixels()`
	+ Pulsar Logic
- `kdiff3 skymap_scanner/server/perform_scan.py cloud_tools/save_pixels.py`
     + not much in common

#### Client Code (`skymap_scanner/client/scan_pixel.py`):
- `kdiff3 skymap_scanner/client/scan_pixel.py python/perform_scan.py`
    + only 8 lines starting with `tray.AddSegment(, "scan_pixel_distributed",`
- `kdiff3 skymap_scanner/client/scan_pixel.py python/traysegments/scan_pixel_distributed.py`
     + a lot of similar code
- `kdiff3 skymap_scanner/client/scan_pixel.py cloud_tools/scan_pixel.py`
     + Pulsar logic

#### Tests & CI
There are Docker-based scripts that are triggered by CI. These need to be updated after the dust settles on this PR. Until then, they will fail.

----
**Edit:** Cross out stuff about metadata, and add an "Update" note
**Edit:** Cross out stuff about client throttling, and add an "Update" note

### CODE REVIEW

**Review by dsschult — COMMENTED** [review]
Things I like:
* proper python packaging
* pushing all the server steps together

Things I don't like:
* inheriting some of the bad design patterns from previous code, to make it more diff-friendly

I can't say anything to the science parts of this, though as long as it produces the same result it should be fine.

**Comment by ric-evans** [comment]
> Things I don't like:
> 
> * inheriting some of the bad design patterns from previous code, to make it more diff-friendly

I agree, the plan is to improve this in a future PR.

**Comment by ric-evans** [comment]
Removed "Metadata" (GCD) frame-logic. See the main description.

**Comment by ric-evans** [comment]
Removed client throttling. See the main description.

**Pull request merged**
