### PR TITLE
Add simple test case scan

### PR DESCRIPTION
**Pull request by ric-evans**
closes https://github.com/icecube/skymap_scanner/issues/6

### CODE REVIEW

**Comment by ric-evans** [comment]
@clagunas can you also add `pycache/` to the `.gitignore`?

**Comment by ric-evans** [comment]
> @clagunas can you also add `pycache/` to the `.gitignore`?

Never mind, I'll make a branch with a full `.gitignore`

**Comment by blaufuss** [comment]
@clagunas are these copies of scan scripts from other areas?  If so, I'd worry if these are updated/tweaked they fall out of sync with the "main scanner" scripts.  Is it not possible to call the production scripts with appropriate options and reduce duplication?

**Comment by clagunas** [comment]
They are modified copies, yes. As it is right now, it's not possible. For some of the functionalities I would have to change the main scripts so that we can parse the options, but for others I don't know if I can. That's why in principle I wasn't planning to merge the two branches. Let me take a look at it this week and see what I can do. Anyway, the changes in those scripts are minimal.

**Comment by ric-evans** [comment]
> They are modified copies, yes. As it is right now, it's not possible. For some of the functionalities I would have to change the main scripts so that we can parse the options, but for others I don't know if I can. That's why in principle I wasn't planning to merge the two branches. Let me take a look at it this week and see what I can do. Anyway, the changes in those scripts are minimal.

If the only differences between the testing scripts and the "main scanner" scripts (those in `resources/scripts/`) are the command-line arguments/options, it could be useful to add a `common_script_utils` folder to the "main scanner" scripts which hold the common classes/functions. Then, import and invoke those as appropriate. Thoughts?

**Comment by dsschult** [comment]
It might also be useful to make a branch with the changes made directly, so we can see a proper diff of the changes.  Even if we never merge that, we could use that diff to see where to make the changes in the future.

Specifically, @ric-evans will likely be taking a chain saw to a large swath of the connecting code, and it might be easier to make the changes for these options during/after that.

**Comment by clagunas** [comment]
I added comments that start with # test-case-scan so that they are easy to track down. The only file that I haven't commented yet is perform_scan because that's the one that changed the most and I'm still looking into it.

**Pull request merged**
