### PR TITLE
Communication Layers Refit

### LINKED ISSUE #5: Clean up repeated files from cloud_tools/ and python/
There are several files that were copied to cloud_tools from old skymap_scanner that appear to be old and/or modified copies of old scripts from ancient versions of skymap_scanner from SVN.  These need a more careful look as things move forward.  I suspect some pieces of these might be needed as things transition to cloud again with modern scan.  But "standard condor" scan will be from python/ and resources/ dirs right now (as they're currently run)

Please consider these repeated files also present in python/:
- cloud_tools/
    config.py
    extract_json_message.py
    perform_scan.py
    scan_pixel.py/scan_pixel_distributed.py (and python/traysegments/scan_pixel_distributed.py)
    utils.py

Several commits from SVN history might be helpful to see what's changed in the Condor scanner since it split:
https://code.icecube.wisc.edu/projects/icecube/log/IceCube/sandbox/ckopper/skymap_scanner?rev=185232

### LINKED ISSUE #13: Clean up of symlinks
Several files in `resources/scripts` are symlinks to `python`. This likely requires a cleanup.

### LINKED ISSUE #27: Divergent versions of `perform_scan.py`
The `perform_scan.py` differs between `cloud_tools` and `python` (see #5).

The `cloud_tools` version is designed to operate with a fixed NSIDE value, while the `python` version has the machinery to perform the hierarchical scan as we do in real time.

The core functionality is provided as an IceTray module named `SendPixelsToScan`.

The input is prepared by `extract_json_message()` (see #26). For `cloud_tools`, this is simply the GCDQp frame packet. For `python`, the `state_dict` is loaded.

The version in `cloud_tools` has added reco functionality (see `get_reco_losses_inside()`). This part could be easily merged.

### PR DESCRIPTION
**Pull request by ric-evans**
Implement MQClient and add simplified GCD communication/transfer

The main files are:
- `skymap_scanner/server/start_scan.py`
	+ takes a realtime pkl event, sends pixels to clients, and saves the best scan for each
	+ think of this as a de-icetray'd `perform_scan.py`
- `skymap_scanner/client/client.py`
	+ the end-point of the pulsar communication
	+ spawns a subprocess for a millipede tray for processing a single pixel (variation)
- `skymap_scanner/client/scan_pixel_pkl.py`
	+ the millipede tray
	+ essentially unchanged from `scan_pixel_distributed.py` (updates from the slack channel)

@mlincett & @dschull: please look at "TODO" comments, most of these are things I haven't figured out

closes #27
closes https://github.com/icecube/skymap_scanner/issues/25
closes #13 (no longer needed)
closes #5 (no longer needed)
closes https://github.com/icecube/skymap_scanner/issues/2

### CODE REVIEW

**Comment by dsschult** [comment]
Is it a good idea to try putting MQClient as IceTray modules?  Or is there a better way to do this outside IceTray?

**Comment by ric-evans** [comment]
> Is it a good idea to try putting MQClient as IceTray modules? Or is there a better way to do this outside IceTray?

This was my plan for the client-side. Is the alternative something like this:

**Comment by ric-evans** [comment]
@dsschult I'm most unsure about how to get the frame/scan out of the tray. But also, I don't know if there's any significant performance cost to building & tearing down icetray for each pixel/incoming-message.

**Comment by kjmeagher** [comment]
There isn't much overhead for instantiating a new tray for every message, but instantiating a lot of trays has been known to cause memory leaks in the past. I am not aware of any problem with having one icetray module listen for messages. and having another module that sends messages after the reconstruction

**Comment by dsschult** [comment]
One other alternative is just taking the hit to starting a subprocess for each msg in the stream.  That's known safe, and if libraries get cached in memory is still fairly fast.

An example for the client:
```python
for in_msg in stream:
  with open('in_msg','w') as f:
    f.write(in_msg)
  subprocess.check_call(['icetray_client.py', 'in_msg', 'out_msg'])
  if os.path.exists('out_msg'):
    with open('out_msg') as f:
      out_msg = f.read()
    back_to_client.send(out_msg)
```

**Comment by ric-evans** [comment]
Note: the `Signals.SIGBUS: 7` error may be due to a serialization bug. Currently, the I3Frame is naively pickled and sent over the wire, the frame once deserialized may have dangling/invalid C++ pointers. We'll need to not send I3Frames, but rather something smaller that can be _made into_ an I3Frame. 

@briedel brought up a similar point in https://github.com/icecube/skymap_scanner/issues/26#issuecomment-1096756587

**Comment by ric-evans** [comment]
CI is working and will be sped up. I am planning to add more components to make the jobs more "test" like

**Review by dsschult — COMMENTED** [review]
I reviewed the three main files, and it looks good to me.

**Comment by ric-evans** [comment]
@mlincett I've largely preserved the reporting and logging callbacks, see `ProgressReporter`. We will need to decide on a design for how to "pass in" the callback functions. This will ultimately depend on how we execute the scanner. The scanner is started as an importable module in the (pre-existing) alert listener (2.0). I don't think this is scalable. Instead, I'd prefer to fire off a subprocess script that will start up the server and n clients. This way if the alert listener goes down, the server is still operational.

**Pull request merged**
